### ISSUE TITLE
worker issue after flutter web build

### ISSUE THREAD

**Issue by okta2510** [jerson/flutter-rsa#21]
build/web/assets/packages/fast_rsa/web/assets/worker.js

worker.js:55 Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
![Screenshot 2021-09-14 at 14 06 06](https://user-images.githubusercontent.com/4715230/133211685-1e7dc3fa-b172-4b9f-a203-e16eaa1e2d8c.png)

**Comment by jerson** [comment]
Hi @okta2510 thanks for you question, this error is because you need to set an extra mine type in your web server, for example if you are using nginx is something like this

```nginx
http {
    include mime.types;
    types {
        application/wasm wasm;
    }
...
}
```
file: https://github.com/jerson/flutter-rsa/blob/master/example/docker/nginx.conf

or in nodejs
```javascript
const express = require('express');
express.static.mime.define({'application/wasm': ['wasm']});
```
file: https://github.com/jerson/rsa-mobile/blob/protobuf/wasm/sample/server.js

BTW we have a running example in https://flutter-rsa.jerson.dev/#/

**Comment by okta2510** [comment]
hi thx for your response ya lately I figure it out, thanks for explaination

**Comment by hbolin** [comment]
When I first loaded the page, there was no problem. But when I refresh the page, I still get this error: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
