### ISSUE TITLE
Performance issue in profile mode

### ISSUE THREAD

**Issue by maltemedocs** [jerson/flutter-rsa#35]
Hi, this is just a heads up. When running Fast RSA in profile mode, that is profile mode started from the IDE, the performance of RSA encrypt and decrypt operations is abysmal compared to its regular profile/release mode performance. This is not a bug in Fast RSA, but a bug in flutter/Dart and its VS Code integration, reported and confirmed in https://github.com/Dart-Code/Dart-Code/issues/3838. It affects at least Android and iOS.

Just wanted to make sure you are aware of the issue and its cause before running into it, if you are not aware of it already (and ofc feel free to close this issue).

**Comment by jerson** [comment]
Hi @maltemedocs thanks for report the issue, I wasn't aware of the problem, but I'll take a closer look, in this library we are using FFI and Isolate.spawn so it may have something to do with it.

**Comment by DanTup** [comment]
The issue wasn't strictly that the code was running more slowly, the issue was that new isolates were spawned _paused_ and had to be unpaused by the debugger. This introduced a small delay which makes things look slower (at least for some ways of timing - the CPU Profiler would probably not be fooled).

The issue is fixed for the next release of the Dart extension for VS Code (and is available in the extensions pre-release channel if you need it sooner) - see https://github.com/Dart-Code/Dart-Code/issues/3838#issuecomment-1047901982.
